name: Format (PHP)

on:
  push:
    branches:
      - '**'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.1'
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Composer dump-autoload
        run: composer dump-autoload
      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix